### PR TITLE
Add new methods for generating OD matrices

### PR DESCRIPTION
**Pull request by yeesian**
that are 2-dimensional; so they're more appropriate for network design than scheduling.

I've introduced a `maxentdemand!()` method which  uses a proportionality weighting approach. It'll be good if you can help review it for correctness

To see how everything comes together, see this [notebook](https://github.com/yeesian/MitsubishiNotebooks/blob/coverage3/notebooks/9b-julia-fulltransit-coverage-analysis.ipynb). (I've tried saving the transitnetwork that we've built to disk, before loading it back into a julia session; it takes up about 4GB on disk, and doesn't seem to load faster than it takes us to build a new one from scratch..)

### CODE REVIEW

**Comment by yeesian** [comment]
> (I've tried saving the transitnetwork that we've built to disk, before loading it back into a julia session; it takes up about 4GB on disk, and doesn't seem to load faster than it takes us to build a new one from scratch..)

I have [another branch](https://github.com/juliayyan/TransitNetworks.jl/commit/7b111688eb79e36cb3c22381a806f6ca155febbf) that switched the integers to uint16 (1/4 of their size) since they aren't going to be that big in value (`typemax(UInt16)==65535)`), but it didn't shrink the size of the transitnetwork by much (still ~4GB on disk), and all the type-coercion makes them harder to work with, so I've decided not to go down that route.

**Comment by yeesian** [comment]
> (I've tried saving the transitnetwork that we've built to disk, before loading it back into a julia session; it takes up about 4GB on disk, and doesn't seem to load faster than it takes us to build a new one from scratch..)

Just for comparison: [valhalla](https://github.com/valhalla) is a routing engine, and [it also takes them a long time to build up a network](https://gist.github.com/JesseCrocker/45680f88cdfda442d3ea4b950435f38b). Admittedly the nature of our networks is different from theirs, but I'm starting to feel less poorly about what we have now, haha.

**Comment by juliayyan** [comment]
I was exploring the data, and have some questions/comments.

**ME implementation**
It looks good.

**Total demand volume**
Just want to see if I'm interpreting this right.  According to your notebook, the 5pm bus demand is 4085.  But it looks like there are 10,040 total entries in at 5pm.  So... over half of the demand is coming from bus stations outside of the key bus routes?
```
entries = zeros(24)
for k in keys(apcdata["entries"])
  stnentries = apcdata["entries"][k]
  for h in keys(stnentries)
    entries[parse(Int, h)+1] += stnentries[h]
  end 
end 
```

**odmatrix is not sparse **
`sum(round.(odmatrix))` (only considering bus demand) is 97!! That is so tiny and not great for us...

**Comment by yeesian** [comment]
To my understanding, the apcdata (which is the data melissa sent us) is based on averaged values, so rounding would kill many of them.

# Non-zeros
If we looked at the OD matrix before melissa's apc data,
```
sum(odmatrix .> 0.001) = 3430
```
3430 of them would be non-zeros. Whereas after including her data,
```
sum(odmatrix .> 0.001) = 588029
```
588029 of them would be non-zeros.

So yes, it makes the matrix a lot denser.

# Total volume
If we looked at the OD matrix before melissa's apc data,
```
sum(odmatrix) = 62283.0
```
The average total volume of commuters is `62283`. After including her data,
```
sum(odmatrix) = 66368.0
```
it didn't increase by that much (around 4100 commuters).

**Comment by yeesian** [comment]
> This is not an issue with this PR, but I'm just concerned that with this really dense but small-valued odmatrix, our models will be very large, but ultimately not actually capturing much useful demand.

Oh haha yeah, I see what you're saying now.. But that's the general problem of sprawl in general right?

**Comment by juliayyan** [comment]
True.  Okay, go ahead and merge if you want.

**Comment by yeesian** [comment]
Let me try to add a test for the maxent function. I'll merge after.

**Pull request merged**
